version: "3.8"

services:
  db:
    image: postgres:14
    container_name: song_list_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - song-list-app-network
    restart: unless-stopped

  app:
    container_name: song_list_next
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
    ports:
      - "3000:3000"
    networks:
      - song-list-app-network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  song-list-app-network:
    driver: bridge
